# Generated by Django 5.1.3 on 2024-11-14 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VagaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Vaga')),
                ('empresa', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Empresa')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('descricao', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descrição')),
            ],
        ),
    ]
